# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN-AkObrWzvwWTc4DHROIlCRVQKUXxIc
"""

import numpy as np
import pandas as pd
from experimentation.metrics import (
    cosine_sim,
    mann_whitney_test,
    cohens_d,
)


def experiment3_lidioms(
    emb_ru: np.ndarray,
    emb_idiomatic: np.ndarray,
    emb_literal: np.ndarray,
    df_lidioms: pd.DataFrame,
):
    """
    Experiment 3: Semantic vs lexical preference.
    """

    sim_idiomatic = cosine_sim(emb_ru, emb_idiomatic)
    sim_literal = cosine_sim(emb_ru, emb_literal)

    diff = sim_idiomatic - sim_literal

    stats = {
        "idiomatic_mean": sim_idiomatic.mean(),
        "literal_mean": sim_literal.mean(),
        "difference_mean": diff.mean(),
        "prop_prefers_idiomatic": (diff > 0).mean(),
        "u_test": mann_whitney_test(
            sim_literal, sim_idiomatic, alternative="greater"
        ),
        "cohens_d": cohens_d(sim_literal, sim_idiomatic),
    }

    detailed = df_lidioms.copy()
    detailed["sim_idiomatic"] = sim_idiomatic
    detailed["sim_literal"] = sim_literal
    detailed["difference"] = diff

    return stats, detailed