# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WHA237-EBfm1Z7qigf_nd2qiNAMtESVt
"""

# -*- coding: utf-8 -*-

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from experimentation.metrics import (
    cosine_sim,
    random_pair_similarity,
    cohens_d,
    retrieval_accuracy,
    pca_analysis,
)


def experiment2_crosslingual(
    emb_ru: np.ndarray,
    emb_en: np.ndarray,
    sentences_ru: list[str],
    sentences_en: list[str],
    seed: int = 42,
):
    """
    Cross-lingual alignment experiment (RU–EN).

    Compares LaBSE embeddings against a TF-IDF lexical baseline.
    """

    rng = np.random.default_rng(seed)

    # --------------------------------------------------
    # LaBSE similarity
    # --------------------------------------------------
    aligned = cosine_sim(emb_ru, emb_en)
    random = random_pair_similarity(emb_ru, emb_en, seed=seed)

    retrieval = {
        k: retrieval_accuracy(emb_ru, emb_en, k)
        for k in [1, 5, 10]
    }

    # --------------------------------------------------
    # TF-IDF baseline (non-semantic)
    # --------------------------------------------------
    all_sentences = sentences_ru + sentences_en

    vectorizer = TfidfVectorizer(
        max_features=20000,
        ngram_range=(1, 2),
        lowercase=True,
    )

    X = vectorizer.fit_transform(all_sentences)

    X_ru = X[:len(sentences_ru)]
    X_en = X[len(sentences_ru):]

    tfidf_aligned = cosine_similarity(X_ru, X_en).diagonal()

    perm = rng.permutation(X_en.shape[0])
    tfidf_random = cosine_similarity(X_ru, X_en[perm]).diagonal()

    # --------------------------------------------------
    # PCA (LaBSE only)
    # --------------------------------------------------
    X_labse = np.vstack([emb_ru, emb_en])
    pca = pca_analysis(X_labse)

    # --------------------------------------------------
    # Results
    # --------------------------------------------------
    results = {
        "aligned_mean": float(aligned.mean()),
        "random_mean": float(random.mean()),
        "cohens_d": cohens_d(aligned, random),
        "retrieval": retrieval,
        "tfidf_aligned_mean": float(tfidf_aligned.mean()),
        "tfidf_random_mean": float(tfidf_random.mean()),
        "pca": pca,
    }

    return results