# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN-AkObrWzvwWTc4DHROIlCRVQKUXxIc
"""

from .labse import LaBSEEncoder