# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8lsP_ugkYr9VZ2HP8zjaGOgQRa-KLIC
"""

from .load_magpie import load_magpie
from .load_idioms_in_context import load_idioms_in_context
from .load_lidioms import load_lidioms