# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN-AkObrWzvwWTc4DHROIlCRVQKUXxIc
"""

import pandas as pd
from typing import Tuple


def load_magpie(
    path: str,
    return_stats: bool = False
) -> pd.DataFrame | Tuple[pd.DataFrame, dict]:
    """
    Load the MAGPIE dataset.
    """
    df_magpie = pd.read_csv(path, sep="\t")

    required_cols = {"sentence", "idiom", "usage", "pos_tags"}
    missing = required_cols - set(df_magpie.columns)
    if missing:
        raise ValueError(f"MAGPIE is missing required columns: {missing}")

    df_magpie = df_magpie[list(required_cols)].copy()
    df_magpie = df_magpie.dropna().reset_index(drop=True)

    df_magpie["usage"] = df_magpie["usage"].str.lower()
    valid_usages = {"literal", "figurative"}
    invalid = set(df_magpie["usage"].unique()) - valid_usages
    if invalid:
        raise ValueError(f"Unexpected usage labels found: {invalid}")

    if not return_stats:
        return df_magpie

    idiom_counts = df_magpie.groupby("idiom")["sentence"].count()

    stats = {
        "num_sentences": len(df_magpie),
        "num_unique_idioms": df_magpie["idiom"].nunique(),
        "avg_examples_per_idiom": idiom_counts.mean(),
        "usage_distribution": df_magpie["usage"].value_counts().to_dict(),
    }

    return df_magpie, stats