# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN-AkObrWzvwWTc4DHROIlCRVQKUXxIc
"""

import pandas as pd
from typing import Tuple


def load_lidioms(
    path: str,
    return_stats: bool = False
) -> pd.DataFrame | Tuple[pd.DataFrame, dict]:

    df_lidioms = pd.read_csv(path)

    required_cols = {"idiom_ru", "definition_en", "literal_en"}
    missing = required_cols - set(df_lidioms.columns)
    if missing:
        raise ValueError(f"LIdioms missing columns: {missing}")

    df_lidioms = df_lidioms[list(required_cols)].copy()
    df_lidioms = df_lidioms.dropna().reset_index(drop=True)

    if not return_stats:
        return df_lidioms

    return df_lidioms, {"num_idioms": len(df_lidioms)}