# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dN-AkObrWzvwWTc4DHROIlCRVQKUXxIc
"""

import pandas as pd
from typing import Tuple


def load_idioms_in_context(
    ru_path: str,
    en_path: str,
    skip_lines: int = 4,
    return_stats: bool = False,
) -> pd.DataFrame | Tuple[pd.DataFrame, dict]:
    """
    Load the IdiomsInContext-MT dataset (Russian–English parallel sentences).

    Parameters
    ----------
    ru_path : str
        Path to the Russian sentences file.
    en_path : str
        Path to the English sentences file.
    skip_lines : int, optional
        Number of initial lines to skip (dataset headers).
    return_stats : bool, optional
        If True, also return basic dataset statistics.

    Returns
    -------
    df_idioms : pd.DataFrame
        DataFrame with parallel sentences:
        - ru_sentence
        - en_sentence
    stats : dict, optional
        Basic dataset statistics.
    """

    # Load sentences
    with open(ru_path, encoding="utf-8") as f:
        ru_sentences = [line.strip() for line in f]

    with open(en_path, encoding="utf-8") as f:
        en_sentences = [line.strip() for line in f]

    # Skip header lines
    if skip_lines > 0:
        ru_sentences = ru_sentences[skip_lines:]
        en_sentences = en_sentences[skip_lines:]

    # Sanity check
    if len(ru_sentences) != len(en_sentences):
        raise ValueError(
            f"Sentence count mismatch: "
            f"RU={len(ru_sentences)}, EN={len(en_sentences)}"
        )

    # Build DataFrame
    df_idioms = pd.DataFrame({
        "ru_sentence": ru_sentences,
        "en_sentence": en_sentences,
    })

    if not return_stats:
        return df_idioms

    stats = {
        "num_pairs": len(df_idioms),
    }

    return df_idioms, stats

